version: '3.8'

services:
  mariaDB :
    image : mariadb
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception

  nginx:
    image: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - mariaDB
    build: requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
    - "443:443"
    restart: always
  
  
  wordpress :
    depends_on: 
      - mariaDB
    image: wordpress
    restart: always
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
  
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aankote/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/aankote/data/mariadb'

networks:
  inception:
    name: inception
    driver: bridge