version: '3.8'

services:
  mariaDB :
    image : mariadb
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception

  nginx:
    image: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - mariaDB
    build: requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
    - "443:443"
    restart: always
  
  wordpress :
    depends_on: 
      - mariaDB
    image: wordpress
    restart: always
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    
  ftp:
    image: ftp
    build: ./requirements/bonus/FTP
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
    env_file:
      - ./.env
    volumes:
      - wordpress:/home/vsftpd/myuser
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8081:8081"
    networks:
      - inception
    restart: always
      
  website:
    image: website
    container_name: website
    build: ./requirements/bonus/website
    ports:
      - "8000:8000"
    networks:
      - inception
    restart: always
    
  ftp-client:
    image: ftp_client
    container_name: ftp_client
    build:  ./requirements/bonus/ftp_client
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - ftp
    restart: always
    networks:
      - inception

  # k3s-master:
  #   build: ./requirements/bonus/Kubernetes
  #   container_name: k3s-master
  #   ports:
  #     - "6443:6443"
  #   networks:
  #     - inception
  #   restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aankote/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/aankote/data/mariadb'


networks:
  inception:
    name: inception
    driver: bridge