FROM debian:11

RUN apt-get update \
    && apt-get install -y nginx \
    && rm -rf /var/lib/apt/lists/*

COPY srcs /var/www/html

COPY ./conf/default.conf /etc/nginx/sites-enabled/default.conf 

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]
