FROM debian:11

EXPOSE 3306

RUN apt -y update && apt -y upgrade

RUN apt -y install mariadb-server

RUN echo "" > /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools /var/tools 

RUN chmod 777 /var/tools/setup.sh
 
CMD ["/var/tools/setup.sh"]