FROM debian:11

RUN apt -y update && apt -y upgrade 

EXPOSE 9000

WORKDIR /var/www/

RUN  apt -y install wget

RUN apt-get install -y php\
                    php-fpm\
                    php-mysql\
                    mariadb-client

COPY ./setup.sh /var/www/

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf


RUN  chmod 777  /var/www/setup.sh

RUN wget https://wordpress.org/latest.tar.gz

RUN tar -xzvf latest.tar.gz

COPY ./conf /var/www/wordpress

# RUN chown -R www-data:www-data /var/www/wordpress
RUN find /var/www/wordpress -type d -exec chmod 777 {} \;
RUN rm -fr latest.tar.gz
CMD ["/var/www/setup.sh"]

# If static assets (like images or CSS files) are requested, 
# Nginx may serve them directly from the mounted volume without
#  involving the WordPress service.

# Dynamic Content Request (e.g., WordPress PHP file):

# Nginx forwards the request to the WordPress service on the inception network.
# The WordPress service processes the PHP file and returns the dynamic content to Nginx.
# Nginx sends the dynamic content back to the browser.