FROM  debian:11

EXPOSE 443

RUN apt -y update && apt -y upgrade

RUN apt install -y openssl \
                   curl -y \ 
                   nginx

RUN mkdir -p /etc/nginx/ssl 

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -nodes -keyout \
    /etc/nginx/ssl/private-key.key -out /etc/nginx/ssl/aankote.42.fr.crt -subj "/"

COPY ./conf/default.conf /etc/nginx/sites-enabled/default.conf 

CMD [ "nginx", "-g", "daemon off;" ]